### ISSUE TITLE
JPA에 막혀서 더이상 진도를 나갈수가 없습니다.

### ISSUE THREAD

**Issue by eraser10** [ahastudio/fastcampus-eatgo#11]
안녕하세요.
fast campus java course를 듣고 있습니다.
현재 03.스프링 부트 프로젝트(어드민 페이지 만들기)를 수강하고 있는데
08.Entity 생성과 Repository에서 진도를 나가지 못하고 있습니다.

MySQL 테이블까지 생성하고 `User.java`에서 

```java
package com.example.study.model.entity;

import javax.persistence.Entity;

@Entity
public class User {
}
```

--- `@Entity`를 입력하게 되면 
public class User문장에서 User에 error가 발생합니다. 해당 에러는 
"`Persistent entity 'User' should have primary key`"

정확하게 MySQL에 "id"는 PK.로 선언이 되어 있습니다.
추즉으로는 환경적인 문제때문에 DB와 연결이 안되는것 같습니다.

몇일째 하고 있는데 더이상 진도를 나가지 못하고 있습니다.
도움 부탁합니다.

**Comment by ahastudio** [comment]
해당 이슈는 제 강의가 아닙니다. 저는 처음에 DB를 사용하지 않는 걸 권장합니다.

**Comment by eraser10** [comment]
죄송합니다.
