### ISSUE TITLE
31 프로젝트 분리-3 에서 코드 누락 된것 같습니다.

### ISSUE THREAD

**Issue by jongyeon95** [ahastudio/fastcampus-eatgo#18]
5분50초 이후부터 `getMenuItems()` 관련된 코드를 작성하면서 문제가 생깁니다.

대표적인 예로 `ReviewControllerTest`에서

```java
public void list() throws Exception {
        mvc.perform(get("/reviews"))
                .andExpect(status().isOk())
                .andExpect(content().string(containsString("Cool!")));
    }
```

강의 영상에서 `/reviews`를 `GetMaping` 한 영상
이 없는데 오류없이 진행되고 있습니다.
현재 프로젝트 분리-2까지는 완료하였으나 분리-3에서 진도를 못나가고 있습니다.

제 코드의 GitHub주소는 
https://github.com/jongyeon95/fastcampusSpring/tree/master/spring-boot-project1(resturant)/eatgo
입니다. 어느 부분이 잘못되었는지 모르겠습니다.

**Comment by ahastudio** [comment]
해당 테스트는 관리자용 API에 해당됩니다. 고객용 API와 `@GetMapping`을 지정한 게 조금 다릅니다.

관리자용 API:
- <https://github.com/ahastudio/fastcampus-eatgo/blob/master/eatgo-admin-api/src/main/java/kr/co/fastcampus/eatgo/interfaces/ReviewController.java>
- <https://github.com/ahastudio/fastcampus-eatgo/blob/master/eatgo-admin-api/src/test/java/kr/co/fastcampus/eatgo/interfaces/ReviewControllerTests.java>

고객용 API:
- <https://github.com/ahastudio/fastcampus-eatgo/blob/master/eatgo-customer-api/src/main/java/kr/co/fastcampus/eatgo/interfaces/ReviewController.java>
- <https://github.com/ahastudio/fastcampus-eatgo/blob/master/eatgo-customer-api/src/test/java/kr/co/fastcampus/eatgo/interfaces/ReviewControllerTests.java>
