### ISSUE TITLE
Java 웹 개발 마스터 올인원 패키지 Online. 22. 에러 처리 강의 문의드립니다.

### ISSUE THREAD

**Issue by jyryuitpro** [ahastudio/fastcampus-eatgo#74]

**Comment by ahastudio** [comment]
이 영상을 참고하세요. → https://www.youtube.com/watch?v=tSjIUn96zlA

다른 내용은 이 링크에서 확인 가능합니다. → https://j.mp/2PWvF8T

**Comment by jyryuitpro** [comment]
감사합니다. 👍 
아샬님 덕분에 스프링부트 프로젝트 너무 재미있게 잘 하고 있습니다.
