### ISSUE TITLE
localhost가 연결을 거부했다고 뜹니다.

### ISSUE THREAD

**Issue by Kim-Junhwan** [ahastudio/fastcampus-eatgo#84]
<img width="910" alt="스크린샷 2020-10-14 오후 6 00 05" src="https://user-images.githubusercontent.com/58679737/95967440-3899c300-0e47-11eb-9b4f-b5489b5fad6e.png">
위 사진처럼 localhost가 연결을 거부했다고 뜹니다. 뭐가 문제일걸까요

**Comment by hh-min** [comment]
Application을 실행하여 포트를 열어주셔야 합니다!!
