### ISSUE TITLE
27강 ReviewService Nullpoint Exception

### ISSUE THREAD

**Issue by youngrimlee04** [ahastudio/fastcampus-eatgo#85]
안녕하세요.

27강 강의 듣던 중 Nullpoint Exception 오류가 나와 질문 드립니다.

아래 ReviewServiceTests.java입니다.

`package com.example.eatgo.application;

import com.example.eatgo.domain.Review;
import com.example.eatgo.domain.ReviewRepository;
import org.junit.Before;
import org.junit.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import static org.junit.Assert.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.verify;

public class ReviewServiceTests {

    private ReviewService reviewService;

    @Mock
    private ReviewRepository reviewRepository;

    @Before
    public void setUp(){
        MockitoAnnotations.initMocks(this);

        reviewService = new ReviewService();
    }

    @Test
    public void addReview(){
        Review review = Review.builder()
                .name("JOKER")
                .score(3)
                .description("Mat-it-da")
                .build();

        reviewService.addReview(review);

        verify(reviewRepository).save(any());
    }

}`

아래 부분에서 expected 1 argument but found 0이라고 나옵니다.

 reviewService = new ReviewService();

테스트 후에는 아래와 같은 오류가 뜹니다.

reviewService = new ReviewService();
                        ^
  required: ReviewRepository
  found: no arguments

진도를 못나가고 있어서요 바쁘시겠지만 확인 부탁 드립니다 ㅠ

감사합니다!

**Comment by hungry-matt** [comment]
ReviewService 인스터스화 할때 ReviewRepository를 인자로 넘겨줘야 하는데 누락된거 같습니다.

해당되는 오류를 아래와 같이 해보시겠어요?

```java
@Before
public void setUp(){
    MockitoAnnotations.initMocks(this);

   reviewService = new ReviewService(reviewRepository);
}
```

**Comment by youngrimlee04** [comment]
아 reviewRepository를 argument로 넣어주니 오류가 나지 않습니다.

감사합니다!
